name: Build MacOS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-macos.yml'
      - 'macos/**'
      - 'lib/**'
      - 'src/**'
      - 'example/macos/**'
      - 'example/lib/**'
      - 'pubspec.yaml'
  workflow_run:
    workflows: ["Update Submodules Daily"]
    types:
      - completed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.APPLE_PASSWORD }}

      - name: Install the provisioning profile
        run: |
          mkdir -p ~/Library/Developer/Xcode/Provisioning\ Profiles
          echo "${{ secrets.APPLE_MACOS_PROVISION_PROFILE }}" | base64 --decode > ~/Library/Developer/Xcode/Provisioning\ Profiles/Github_Actions.provisionprofile

      - name: Build macOS App
        run: |
          cd example
          flutter pub get
          flutter build macos -v

      - name: Sign macOS App
        run: |
          codesign --deep --force --verbose --options runtime --timestamp --sign "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" example/build/macos/Build/Products/Release/lcpp_example.app

          find example/build/macos/Build/Products/Release/lcpp_example.app -type d -name "*.framework" -exec codesign --force --verbose --options runtime --timestamp --sign "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" {} \;
          find example/build/macos/Build/Products/Release/lcpp_example.app -type f -exec codesign --force --verbose --options runtime --timestamp --sign "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" {} \;

          codesign --verify --deep --strict --verbose example/build/macos/Build/Products/Release/lcpp_example.app

      - name: Compress macOS App
        run: |
          ditto -c -k --sequesterRsrc --keepParent "example/build/macos/Build/Products/Release/lcpp_example.app" "lcpp_example.zip" 

      - name: Notarize macOS App
        run: |
          xcrun notarytool store-credentials --apple-id ${{ secrets.APPLE_ID }} --password ${{ secrets.APPLE_APPLICATION_SPECIFIC_PASSWORD }} --team-id ${{ secrets.APPLE_TEAM_ID }} --validate notorization_profile
          xcrun notarytool submit --keychain-profile "notorization_profile" --progress --wait lcpp_example.zip

      - name: Staple Notarization Ticket
        run: |
          xcrun stapler staple "example/build/macos/Build/Products/Release/lcpp_example.app"

      - name: Create DMG
        run: ./scripts/create-dmg.sh ${{ matrix.os == 'macos-13' && 'x86_64' || 'arm64' }}

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: lcpp_example-macos-${{ matrix.os == 'macos-13' && 'x86_64' || 'arm64' }}
          path: dmg